import gql from 'graphql-tag';

export const ADD_STUDENT = gql`
  mutation saveStudent($input: StudentInput) {
    saveStudent(input: $input) {
      cmsStudentVo {
        id
        studentName
        studentMiddleName
        studentLastName
        fatherName
        fatherMiddleName
        fatherLastName
        motherName
        motherMiddleName
        motherLastName
        studentAadharNo
        studentPanNo
        studentSocialSecurityNo
        studentTaxReferenceNo
        studentBplNo
        studentDrivingLicenseNo
        studentPassportNo
        dateOfBirth
        placeOfBirth
        religion
        caste
        subCaste
        age
        sex
        studentLocalAddress
        studentPermanentAddress
        city
        state
        country
        pinCode
        studentPrimaryCellNumber
        studentAlternateCellNumber
        studentLandLinePhoneNumber
        studentPrimaryEmailId
        studentAlternateEmailId
        emergencyContactEmailId
        relationWithStudent
        emergencyContactName
        emergencyContactMiddleName
        emergencyContactLastName
        emergencyContactCellNumber
        emergencyContactLandLinePhoneNumber
        emergencyContactEmailId
        studentImagePath
        admissionNo
        enrollmentNo
        rollNo
        studentType
        fatherCellNumber
        fatherEmailId
        fatherOccupation
        fatherOfficeEmailId
        fatherOfficeAddress
        fatherOfficeCellNumber
        fatherOfficeLandLinePhoneNumber
        fatherAadharNo
        fatherPanNo
        fatherSocialSecurityNo
        fatherTaxReferenceNo
        fatherBplNo
        motherDrivingLicenseNo
        fatherPassportNo
        fatherImagePath
        motherCellNumber
        motherEmailId
        motherOccupation
        motherOfficeEmailId
        motherOfficeAddress
        motherOfficeCellNumber
        guardianOfficeLandLinePhoneNumber
        guardianEmailId
        guardianOccupation
        guardianOfficeEmailId
        guardianOfficeAddress
        guardianOfficeCellNumber
        guardianOfficeLandLinePhoneNumber
        guardianImagePath
        isGuardianSponsorAgency
        sponsorAgencyName
        sponsorAgencyRegistrationNo
        sponsorAgencyAddress
        sponsorAgencyCellNumber
        sponsorAgencyLandLineNumber
        sponsorAgencyEmailId
        sponsorAgencyAppointeeName
        sponsorAgencyAppointeeDesignation
        sponsorAgencyAppointeeCellNumber
        sponsorAgencyAppointeeLandLineNumber
        sponsorAgencyAppointeeEmailId
        sponsorAgencyAppointeeOfficeAddress
        isPhysicallyChallenged
        detailsOfDisability
        disabilityCertificateNo
        disabilityCertificateIssueAuthority
        disabilityCertificateIssueDate
        percentagOfDisability
        bloodGroup
        vaccinationDetails
        otherMedicalDetails
        status
        comments
        departmentId
        batchId
        sectionId
        branchId
      }
    }
  }
`;
